<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <DSPRoot Condition="'$(DSPRoot)' == ''">E:\Steam\steamapps\common\Dyson Sphere Program</DSPRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil"><HintPath>$(DSPRoot)/BepInEx/core/Mono.Cecil.dll</HintPath></Reference>
  </ItemGroup>
</Project>
