<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/DSPDreamer.Recorder/ModelAction.cs" Link="ModelAction.cs" />
    <Compile Include="../../src/DSPDreamer.Recorder/Json.cs" Link="Json.cs" />
  </ItemGroup>
</Project>
