<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Compile Include="StorageSmoke.cs" />
    <Compile Include="../issue-4-recorder/PrototypeFrameStorage.cs" Link="PrototypeFrameStorage.cs" />
  </ItemGroup>
</Project>
